behaviors:
  AutoPlayer:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 1.0e-3          # lower entropy
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      shared_critic: false
      learning_rate_schedule: linear
    checkpoint_interval: 500000
    network_settings:
      normalize: true        # normalize obs
      hidden_units: 256
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: true
          hidden_units: 128
          num_layers: 2
      curiosity:             # add curiosity for exploration
        strength: 0.02       # small encouragement to explore
        gamma: 0.99
        network_settings:
          hidden_units: 128
          num_layers: 2
    keep_checkpoints: 5
    max_steps: 2000000
    time_horizon: 128        # longer horizon (better credit assignment)
    summary_freq: 50000
